# Tensors

Tensors are very similar to arrays and matrices and are used in PyTorch to encode inputs and outputs of a model, as well as the model's parameters.

In [4]:
import torch
import numpy as np

## Directly from data

Tensors can be created directly from data. 
The data type is automatically inferred.

In [8]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# From a NumPy array

Tensors can be created from NumPy arrays (and vice versa)

In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# From another tensor

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overwriten.

In [10]:
x_ones = torch.ones_like(x_data)    # retains the properties of x_data
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.randn_like(x_data, dtype=torch.float)    # overrides the datatype of x_data
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[-0.8587, -0.7996],
        [ 0.5604, -0.8336]]) 



# With random or constant values:

`shape` is a tuple of tensor dimensions.
In the function below, it determines the dimensionality of the output tensor.

In [12]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2457, 0.0022, 0.2273],
        [0.1490, 0.7234, 0.8806]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of Tensors

Tensor attributes  describe their shape, datatype, and the device on which they are stored.

In [16]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on : {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on : cpu


## Operations on Tensors

By default, tensors are created on the CPU. 
We need to explicitly move to the GPU using `.to` method (after checking for GPU availability).
Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!


In [21]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('should not be reached on the macbook')
    tensor = tensor.to('cuda')

# Joining tensors

To concatenate tensors, `torch.cat` can be used along with a given dimension.
There is also `torch.stack` which is slightly different.

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.3390, 0.9943, 0.1728, 0.6277, 0.3390, 0.9943, 0.1728, 0.6277, 0.3390,
         0.9943, 0.1728, 0.6277],
        [0.5926, 0.0129, 0.9190, 0.0020, 0.5926, 0.0129, 0.9190, 0.0020, 0.5926,
         0.0129, 0.9190, 0.0020],
        [0.8280, 0.5154, 0.2467, 0.0661, 0.8280, 0.5154, 0.2467, 0.0661, 0.8280,
         0.5154, 0.2467, 0.0661]])


# Arithmetic operations

In [24]:
# This computes the matrix multiplication between two tensors.
# y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. 
# z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1.1492e-01, 9.8864e-01, 2.9874e-02, 3.9397e-01],
        [3.5120e-01, 1.6534e-04, 8.4448e-01, 3.8415e-06],
        [6.8560e-01, 2.6564e-01, 6.0855e-02, 4.3716e-03]])

# Single-element tensors

If you have a single one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical vlaue usint `item()`:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(f'{agg} -- {type(agg)}')
print(f'{agg_item} -- {type(agg_item)}')